# ✅ Lexicón mejorado para detectar emociones en lenguaje real

# Palabras relacionadas con INCERTIDUMBRE
INCERTIDUMBRE = {
    "no sé",
    "nose",
    "no se",
    "no estoy seguro",
    "no estoy segura",
    "tal vez",
    "quizá",
    "quiza",
    "quizas",
    "capaz",
    "dudo",
    "incertidumbre",
    "preocupado",
    "preocupada",
    "preocupacion",
    "preocupación",
    "no tengo idea",
    "no estoy seguro",
    "no tengo claro",
    "no confío",
    "no confio",
    "miedo al futuro",
    "futuro incierto",
    "qué pasará",
    "que pasara",
    "que va a pasar",
    "no se que hacer",
    "no sé qué hacer",
}

# Palabras relacionadas con ANSIEDAD / ESTRÉS
ANSIEDAD = {
    "ansiedad",
    "ansioso",
    "ansiosa",
    "nervioso",
    "nerviosa",
    "me tiembla",
    "estrés",
    "estres",
    "estresado",
    "estresada",
    "angustia",
    "angustiado",
    "ataque de pánico",
    "panico",
    "taquicardia",
    "no puedo respirar",
    "me siento presionado",
    "estres mental",
    "ansiedad pura",
    "no puedo dormir",
    "tengo miedo",
    "tengo ansiedad",
    "me da ansiedad",
    "angustiado",
}

# Palabras relacionadas con DEPRESIÓN / TRISTEZA
DEPRESION = {
    "depresion",
    "depresión",
    "deprimido",
    "deprimida",
    "sin ganas",
    "no quiero seguir",
    "triste",
    "tristeza",
    "me siento vacío",
    "vacio",
    "nada tiene sentido",
    "no encuentro sentido",
    "desesperanza",
    "cansado de todo",
    "harto de todo",
    "vacío por dentro",
    "no me importa nada",
    "quiero desaparecer",
    "me quiero rendir",
    "llorar",
    "me siento solo",
    "siento que nada",
    "todo me da igual",
    "agotado mentalmente",
}

CATEGORIES = {
    "incertidumbre": INCERTIDUMBRE,
    "ansiedad": ANSIEDAD,
    "depresion": DEPRESION,
}
